on: [push]

jobs:  
  k6_local_test:
    name: k6 local test run
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Local k6 test - basic example
      run: k6 run script.js
