on: [push]

jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run k6 cloud test
        uses: k6io/action@v0.1
        with:
          cloud: true
          filename: cloud/script.js
        env:
          K6_CLOUD_TOKEN: ${{ secrets.k6_cloud_token }}
