name: Cloud Workflow
on: [push]

jobs:
  build:
    name: Run k6 cloud test
    runs-on: ubuntu-latest
    environment: cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: cloud/script.js
          cloud: true
          token: ${{ K6_CLOUD_TOKEN }}
