name: Docker Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - docker example
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Local k6 test
        run: k6 run --out json=output/results.json docker/script.js

      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: output/results.json
