on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - using js modules example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Local k6 test with js modules
        uses: k6io/action@v0.1
        with:
          filename: modules/script.js
